CREATE TABLE IF NOT EXISTS order_product
(
    quantity integer not null,
    order_id bigint not null,
    product_id bigint not null

);

CREATE TABLE IF NOT EXISTS orders
(
    id bigint generated by default as identity,
    date_created date,
    status varchar(255)
);

CREATE TABLE IF NOT EXISTS product
(
    id bigint generated by default as identity,
    name varchar(255) not null,
    picture_url varchar(255),
    price double precision
);